"use client";

import React, { useState } from "react";
import { Sparkles, Zap, Plus, Upload } from "lucide-react";
import styles from "./page.module.css";
import toast from "react-hot-toast";

export default function AddCarPage() {
  const [formData, setFormData] = useState({
    title: "",
    shortDescription: "",
    fullDescription: "",
    price: "",
    category: "Hypercar",
  });

  const [imageUrl, setImageUrl] = useState("");
  const [images, setImages] = useState<string[]>([]);
  const [aiText, setAiText] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleAddImage = () => {
    if (imageUrl.trim() !== "" && images.length < 5) {
      setImages((prev) => [...prev, imageUrl.trim()]);
      setImageUrl("");
    }
  };

  const handleSubmit = async () => {
    try {
      setIsSubmitting(true);
      
      const payload = {
        title: formData.title,
        shortDescription: formData.shortDescription,
        fullDescription: formData.fullDescription,
        price: Number(formData.price),
        category: formData.category,
        images: images,
        aiTags: [], // Empty for now, would be generated by AI module
      };

      const res = await fetch("http://localhost:4000/api/cars", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Failed to publish listing");
      }

      toast.success("Listing published successfully!");
      // Reset form
      setFormData({
        title: "",
        shortDescription: "",
        fullDescription: "",
        price: "",
        category: "Hypercar",
      });
      setImages([]);
    } catch (error: any) {
      toast.error(error.message || "An error occurred");
      console.error(error);
    } finally {
      setIsSubmitting(false);
    }
  };

  // Calculate completeness purely for visual effect based on fields filled
  const filledFields = [
    formData.title,
    formData.shortDescription,
    formData.fullDescription,
    formData.price,
  ].filter(Boolean).length;
  const completeness = Math.min(100, Math.round((filledFields / 4) * 60 + (images.length > 0 ? 40 : 0)));

  return (
    <div className={styles.pageContainer}>
      <div className={styles.layoutGrid}>
        
        {/* Left Column: Form Container */}
        <div>
          <div className={styles.header}>
            <div className={styles.subheading}>INVENTORY MANAGEMENT</div>
            <h1 className={styles.heading}>Add New Car</h1>
            <p className={styles.description}>
              List a new vehicle on the high-performance MOTORA marketplace. 
              Ensure technical specifications are precise.
            </p>
          </div>

          <div className={styles.glassPanel}>
            <div className={styles.formGroup}>
              <label className={styles.label}>TITLE</label>
              <input
                name="title"
                value={formData.title}
                onChange={handleInputChange}
                className={styles.input}
                placeholder="e.g. 2024 Aventador SVJ - Hyperion Edition"
              />
            </div>

            <div className={styles.formGroup}>
              <label className={styles.label}>SHORT DESCRIPTION</label>
              <input
                name="shortDescription"
                value={formData.shortDescription}
                onChange={handleInputChange}
                className={styles.input}
                placeholder="One-sentence technical summary"
              />
            </div>

            <div className={styles.formGroup}>
              <label className={styles.label}>FULL DESCRIPTION</label>
              <textarea
                name="fullDescription"
                value={formData.fullDescription}
                onChange={handleInputChange}
                className={`${styles.input} ${styles.textarea}`}
                placeholder="Detailed engineering specs, history, and modifications..."
              />
            </div>

            <div className={styles.formGroup}>
              <label className={styles.label}>PRICE ($)</label>
              <input
                name="price"
                type="number"
                value={formData.price}
                onChange={handleInputChange}
                className={styles.input}
                placeholder="500,000"
              />
            </div>

            <div className={styles.formGroup}>
              <label className={styles.label}>CATEGORY</label>
              <select
                name="category"
                value={formData.category}
                onChange={handleInputChange}
                className={`${styles.input} ${styles.select}`}
              >
                <option value="Hypercar">Hypercar</option>
                <option value="Supercar">Supercar</option>
                <option value="Sports Car">Sports Car</option>
                <option value="Luxury">Luxury</option>
              </select>
            </div>

            <div className={styles.formGroup}>
              <label className={styles.label}>IMAGE URLS</label>
              <div className={styles.imageInputRow}>
                <input
                  value={imageUrl}
                  onChange={(e) => setImageUrl(e.target.value)}
                  className={styles.input}
                  placeholder="https://cdn.motora.io/assets/img_01.jpg"
                />
                <button type="button" onClick={handleAddImage} className={styles.addButton}>
                  Add
                </button>
              </div>

              <div className={styles.thumbnailGrid}>
                {[...Array(5)].map((_, i) => (
                  <div key={i} className={styles.thumbnail}>
                    {images[i] ? (
                      <img src={images[i]} alt={`Preview ${i + 1}`} />
                    ) : (
                      <Upload size={24} />
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Stacked Modules */}
        <div style={{ display: "flex", flexDirection: "column", gap: "2rem", marginTop: "8.5rem" }}>
          
          {/* AI Module */}
          <div className={styles.glassPanel}>
            <h2 className={styles.moduleTitle}>
              <Sparkles size={20} color="#00f0ff" />
              AI AUTO-CLASSIFICATION
            </h2>
            <p className={styles.description} style={{ fontSize: "0.875rem", marginBottom: "1rem" }}>
              Paste a raw manufacturer description or owner notes below. Our neural engine will extract technical specs and auto-fill your listing.
            </p>
            <textarea
              value={aiText}
              onChange={(e) => setAiText(e.target.value)}
              className={`${styles.input} ${styles.aiTextarea}`}
              placeholder="Paste raw text here..."
            />
            <button type="button" className={styles.aiButton}>
              <Zap size={18} fill="#00f0ff" />
              RUN AI ANALYSIS
            </button>
          </div>

          {/* Summary Module */}
          <div className={styles.glassPanel}>
            <h2 className={styles.moduleTitle}>Review Summary</h2>
            <div className={styles.summaryRow}>
              <span className={styles.summaryLabel}>COMPLETENESS</span>
              <span className={styles.summaryValue}>{completeness}%</span>
            </div>
            <div className={styles.summaryRow}>
              <span className={styles.summaryLabel}>IMAGES</span>
              {images.length > 0 ? (
                <span className={styles.summaryValue}>{images.length}/5</span>
              ) : (
                <span className={styles.summaryHighlight}>IMAGE ASSETS REQUIRED</span>
              )}
            </div>
          </div>

          {/* Actions */}
          <div>
            <button 
              type="button" 
              onClick={handleSubmit} 
              className={styles.publishButton}
              disabled={isSubmitting}
            >
              {isSubmitting ? "PUBLISHING..." : "PUBLISH LISTING"}
            </button>
            <a href="#" className={styles.draftLink}>Save to Drafts</a>
          </div>

        </div>

      </div>
    </div>
  );
}
