"use client";

import React, { useState, useRef, DragEvent } from "react";
import { Sparkles, Zap, Upload, X, Loader2, Image as ImageIcon } from "lucide-react";
import styles from "./page.module.css";
import toast from "react-hot-toast";
import { authClient } from "@/app/lib/auth-client";

export default function AddCarPage() {
  const [formData, setFormData] = useState({
    title: "",
    shortDescription: "",
    fullDescription: "",
    price: "",
    category: "Hypercar",
  });

  const [images, setImages] = useState<string[]>([]);
  const [isUploading, setIsUploading] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [aiText, setAiText] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const { data: session } = authClient.useSession();

  const generateAiDescription = async () => {
    if (!formData.title) {
      toast.error("Please enter a title first so AI knows what car to describe.");
      return;
    }

    setIsGenerating(true);
    const loadingToast = toast.loading("AI is writing description...");

    try {
      const res = await fetch("http://localhost:4000/api/ai/generate-description", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: formData.title, category: formData.category }),
      });

      const data = await res.json();
      if (data.success) {
        setFormData(prev => ({ ...prev, fullDescription: data.data.description }));
        toast.success("Description generated!", { id: loadingToast });
      } else {
        throw new Error(data.message || "Failed to generate");
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to generate description", { id: loadingToast });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const uploadToImgbb = async (file: File) => {
    if (images.length >= 5) {
      toast.error("Maximum 5 images allowed");
      return;
    }
    
    setIsUploading(true);
    const loadingToast = toast.loading("Uploading image...");
    
    try {
      const formData = new FormData();
      formData.append("image", file);
      
      const apiKey = process.env.NEXT_PUBLIC_IMGBB_API_KEY;
      if (!apiKey) throw new Error("ImgBB API key is missing in .env.local");

      const res = await fetch(`https://api.imgbb.com/1/upload?key=${apiKey}`, {
        method: "POST",
        body: formData,
      });
      
      const data = await res.json();
      if (data.success) {
        setImages(prev => [...prev, data.data.url]);
        toast.success("Image uploaded successfully!", { id: loadingToast });
      } else {
        throw new Error(data.error?.message || "Upload failed");
      }
    } catch (error: any) {
      toast.error(error.message || "Failed to upload image", { id: loadingToast });
      console.error(error);
    } finally {
      setIsUploading(false);
    }
  };

  const onDragOver = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const onDragLeave = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
  };

  const onDrop = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      const file = e.dataTransfer.files[0];
      if (file.type.startsWith("image/")) {
        uploadToImgbb(file);
      } else {
        toast.error("Please drop an image file");
      }
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      uploadToImgbb(e.target.files[0]);
    }
  };

  const removeImage = (indexToRemove: number) => {
    setImages(prev => prev.filter((_, idx) => idx !== indexToRemove));
  };

  const handleSubmit = async () => {
    try {
      setIsSubmitting(true);
      
      const payload = {
        title: formData.title,
        shortDescription: formData.shortDescription,
        fullDescription: formData.fullDescription,
        price: Number(formData.price),
        category: formData.category,
        images: images,
        aiTags: [], // Empty for now, would be generated by AI module
      };

      const res = await fetch("http://localhost:4000/api/cars", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer user_${session?.user?.id || 'anon'}`
        },
        body: JSON.stringify(payload),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || "Failed to publish listing");
      }

      toast.success("Listing published successfully!");
      // Reset form
      setFormData({
        title: "",
        shortDescription: "",
        fullDescription: "",
        price: "",
        category: "Hypercar",
      });
      setImages([]);
    } catch (error: any) {
      toast.error(error.message || "An error occurred");
      console.error(error);
    } finally {
      setIsSubmitting(false);
    }
  };

  // Calculate completeness purely for visual effect based on fields filled
  const filledFields = [
    formData.title,
    formData.shortDescription,
    formData.fullDescription,
    formData.price,
  ].filter(Boolean).length;
  const completeness = Math.min(100, Math.round((filledFields / 4) * 60 + (images.length > 0 ? 40 : 0)));

  return (
    <div className={styles.pageContainer}>
      <div className={styles.layoutGrid}>
        
        {/* Left Column: Form Container */}
        <div>
          <div className={styles.header}>
            <div className={styles.subheading}>INVENTORY MANAGEMENT</div>
            <h1 className={styles.heading}>Add New Car</h1>
            <p className={styles.description}>
              List a new vehicle on the high-performance MOTORA marketplace. 
              Ensure technical specifications are precise.
            </p>
          </div>

          <div className={styles.glassPanel}>
            <div className={styles.formGroup}>
              <label className={styles.label}>TITLE</label>
              <input
                name="title"
                value={formData.title}
                onChange={handleInputChange}
                className={styles.input}
                placeholder="e.g. 2024 Aventador SVJ - Hyperion Edition"
              />
            </div>

            <div className={styles.formGroup}>
              <label className={styles.label}>SHORT DESCRIPTION</label>
              <input
                name="shortDescription"
                value={formData.shortDescription}
                onChange={handleInputChange}
                className={styles.input}
                placeholder="One-sentence technical summary"
              />
            </div>

            <div className={styles.formGroup}>
              <div className="flex items-center justify-between mb-2">
                <label className={`${styles.label} mb-0`}>FULL DESCRIPTION</label>
                <button
                  type="button"
                  onClick={generateAiDescription}
                  disabled={isGenerating}
                  className="flex items-center gap-1.5 rounded-full bg-gradient-to-r from-[#00D2FF]/20 to-[#0055FF]/20 px-3 py-1 text-xs font-bold text-[#00D2FF] border border-[#00D2FF]/30 hover:bg-[#00D2FF] hover:text-[#0B1120] transition-colors disabled:opacity-50"
                >
                  {isGenerating ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
                  {isGenerating ? "Generating..." : "Auto-generate with AI"}
                </button>
              </div>
              <textarea
                name="fullDescription"
                value={formData.fullDescription}
                onChange={handleInputChange}
                className={`${styles.input} ${styles.textarea}`}
                placeholder="Detailed engineering specs, history, and modifications..."
              />
            </div>

            <div className={styles.formGroup}>
              <label className={styles.label}>PRICE ($)</label>
              <input
                name="price"
                type="number"
                value={formData.price}
                onChange={handleInputChange}
                className={styles.input}
                placeholder="500,000"
              />
            </div>

            <div className={styles.formGroup}>
              <label className={styles.label}>CATEGORY</label>
              <select
                name="category"
                value={formData.category}
                onChange={handleInputChange}
                className={`${styles.input} ${styles.select}`}
              >
                <option value="Hypercar">Hypercar</option>
                <option value="Supercar">Supercar</option>
                <option value="Sports Car">Sports Car</option>
                <option value="Luxury">Luxury</option>
              </select>
            </div>

            <div className={styles.formGroup}>
              <label className={styles.label}>CAR IMAGES (MAX 5)</label>
              
              <div 
                className={`${styles.dropzone} ${isDragging ? styles.dropzoneActive : ""}`}
                onDragOver={onDragOver}
                onDragLeave={onDragLeave}
                onDrop={onDrop}
                onClick={() => fileInputRef.current?.click()}
              >
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleFileSelect} 
                  accept="image/*" 
                  className="hidden" 
                />
                {isUploading ? (
                  <Loader2 className="h-8 w-8 animate-spin text-[#00f0ff]" />
                ) : (
                  <>
                    <Upload className="h-8 w-8 text-[#00f0ff]" />
                    <span className={styles.dropzoneText}>Drag & drop an image here</span>
                    <span className={styles.dropzoneSubtext}>or click to browse from your computer</span>
                  </>
                )}
              </div>

              <div className={styles.thumbnailGrid}>
                {[...Array(5)].map((_, i) => (
                  <div key={i} className={styles.thumbnail}>
                    {images[i] ? (
                      <>
                        <img src={images[i]} alt={`Uploaded ${i + 1}`} />
                        <button 
                          type="button"
                          className={styles.removeButton}
                          onClick={() => removeImage(i)}
                        >
                          <X size={14} />
                        </button>
                      </>
                    ) : (
                      <ImageIcon size={24} opacity={0.3} />
                    )}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Stacked Modules */}
        <div style={{ display: "flex", flexDirection: "column", gap: "2rem", marginTop: "8.5rem" }}>
          
          {/* AI Module */}
          <div className={styles.glassPanel}>
            <h2 className={styles.moduleTitle}>
              <Sparkles size={20} color="#00f0ff" />
              AI AUTO-CLASSIFICATION
            </h2>
            <p className={styles.description} style={{ fontSize: "0.875rem", marginBottom: "1rem" }}>
              Paste a raw manufacturer description or owner notes below. Our neural engine will extract technical specs and auto-fill your listing.
            </p>
            <textarea
              value={aiText}
              onChange={(e) => setAiText(e.target.value)}
              className={`${styles.input} ${styles.aiTextarea}`}
              placeholder="Paste raw text here..."
            />
            <button type="button" className={styles.aiButton}>
              <Zap size={18} fill="#00f0ff" />
              RUN AI ANALYSIS
            </button>
          </div>

          {/* Summary Module */}
          <div className={styles.glassPanel}>
            <h2 className={styles.moduleTitle}>Review Summary</h2>
            <div className={styles.summaryRow}>
              <span className={styles.summaryLabel}>COMPLETENESS</span>
              <span className={styles.summaryValue}>{completeness}%</span>
            </div>
            <div className={styles.summaryRow}>
              <span className={styles.summaryLabel}>IMAGES</span>
              {images.length > 0 ? (
                <span className={styles.summaryValue}>{images.length}/5</span>
              ) : (
                <span className={styles.summaryHighlight}>IMAGE ASSETS REQUIRED</span>
              )}
            </div>
          </div>

          {/* Actions */}
          <div>
            <button 
              type="button" 
              onClick={handleSubmit} 
              className={styles.publishButton}
              disabled={isSubmitting}
            >
              {isSubmitting ? "PUBLISHING..." : "PUBLISH LISTING"}
            </button>
            <a href="#" className={styles.draftLink}>Save to Drafts</a>
          </div>

        </div>

      </div>
    </div>
  );
}
